# If true, first time challenge completions are broadcast to the whole server.
broadcastCompletion: true

# If true, island rankups are broadcast to the whole server.
broadcastRankup: false

# The formatting of the broadcast text.
broadcastFormat: '&b'

# If true, challenges in higher level ranks require challenges in lower level ranks to be completed.
requirePreviousRank: true

# The number of tasks per rank that can be left uncompleted to advance to the next rank. For example, if you have 4 easy challenges
# with a rankLeeway of 1, a player would only need to complete 3 to advance to the next rank.
# A rankLeeway of 0 would require them all.
rankLeeway: 2

# Wether or not to ignore stacked challenges for ranking.
rankIgnoreStacked: true

# The time in hours before required items reset to default.
defaultResetInHours: 20

# If false, challenges are not reset on island creation or restart.
resetChallenges: true

# Material to show for locked challenges
lockedDisplayItem: RED_STAINED_GLASS_PANE

# Whether or not to show the name of locked challenges
showLockedChallengeName: true

# What sound to play when a challenge can't be completed
# Set to null for no sound
noCompleteSound: ENTITY_ITEM_BREAK

# What sound to play when a challenge is completed
# Set to null for no sound
completeSound: ENTITY_FIREWORK_ROCKET_BLAST_FAR

# Whether or not to clear player inventory on island creation/restart.
clearPlayerInventory: true

# Whether or not to show a players rank.
showRank: true

# Material to display in the GUI for the next page and the previous page.
nextPageMaterial: REDSTONE_TORCH
prevPageMaterial: LEVER

MySQL:
  enabled: true
  host: localhost
  port: 3306
  database: skyblock_challenges
  username: alchemi
  password: YouWillBeUpgraded